# list: sources/list.c
# 	gcc -o list sources/list.c
sources: list queue stack

list: sources/list.c
	gcc -o list sources/list.c
queue: sources/queue.c
	gcc -o queue sources/queue.c
stack: sources/stack.c
	gcc -o stack sources/stack.c

clean:
	rm list
	rm queue
	rm stack